apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
      - name: cicd
        image: docker.io/your-docker-username/cicd:2493ba371602d2aa7bc0e2ff34a289c6c9b390d4
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd
  namespace: default
spec:
  selector:
    app: cicd
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
